### ISSUE TITLE
404 when installing blender

### ISSUE THREAD

**Issue by yankov** [Chasvortex/caffe-gui-tool#2]
After running `sudo add-apt-repository ppa:irie/blender && sudo apt-get update` I'm getting this:

```
W: Failed to fetch http://ppa.launchpad.net/irie/blender/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found                                                                                                                                                                                             
W: Failed to fetch http://ppa.launchpad.net/irie/blender/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found
```

**Comment by hctomkins** [comment]
You can download it from blender.org. Extract the archive, run the executable binary, and follow the readme from where blender has been launched. (Start at step 3)

In the meantime I am working on a version that does not require it, or need any setup. After downloading and unpacking, you should be able to find the blender executable. It all looks very complicated when it opens, but you should be fine if you follow the readme. Let me know if you run into any other difficulties.

**Comment by yankov** [comment]
Oh, you are remaking it without blender? I started looking into this as well, but wanted to use flask + d3, so it could be merged to caffe as a tool and then here https://github.com/NVIDIA/DIGITS/issues/60. If you have the same goal in mind and committed already I'd pass ;)

**Comment by hctomkins** [comment]
The idea is to strip down blender to only it's built in node editor, however there would even then be a dependency on some libraries, so I am looking to remaking it. Flask and d3 sounds like a very good idea, although I have little experience with them. One of the files here deals with all the node templates for interfacing with caffe's prototxt and Python - so feel free to use that for your efforts. I may start a flask and D3 branch of caffe gui tool once I get a bit of experience!

**Comment by hctomkins** [comment]
I've decided to keep blender for the minute - its ease of expandability and python interface are for the minute unbeatable. I've made a video tutorial on installation and setup if you are struggling, its three minutes long! Head over to http://chasvortex.github.io/caffe-gui-tool/
