### ISSUE TITLE
error when "Load Solution" is clicked

### ISSUE THREAD

**Issue by aurotripathy** [Chasvortex/caffe-gui-tool#3]
I'm on Blender 2.76b.

I've loaded the following prototxt files from the caffe examples.

/home/tempuser/caffe/examples/cifar10/cifar10_full.prototxt
/home/tempuser/caffe/examples/cifar10/cifar10_full_solver.prototxt

I get the following message.

Traceback (most recent call last):
  File "/home/tempuser/blender/blender-2.76b-linux-glibc211-x86_64/2.76/scripts/addons/caffe-gui-tool/IOloadprototxt.py", line 391, in execute
    LoadFunction(prototxt, y, x)
UnboundLocalError: local variable 'y' referenced before assignment

**Comment by hctomkins** [comment]
Hi!
Thanks for including the error - it should be fixed now. If I somehow managed to botch it let me know but it now works for me. I thought I had made the deployscript path optional but I managed to forget a couple of things. You can leave it blank if you wish now.

To update just do a git pull in your scripts path

**Comment by hctomkins** [comment]
Also note that while the name at the bottom changes to loaded, the tree window will stay blank until you manually select the loaded tree. Sadly no way around this!

**Comment by aurotripathy** [comment]
Thanks for this tip. 
Makes a big difference from staring at a blank screen to looking at the graph!
-Auro
