### ISSUE TITLE
BatchNorm support

### ISSUE THREAD

**Issue by thnkim** [Chasvortex/caffe-gui-tool#4]
Hello,
Do you have a plan to support a new layer type, BatchNorm?
Thank you.

**Comment by hctomkins** [comment]
Hi,
I will add it in later today, if you give me an example of a batchnorm layer in the prototxt, and tell me a bit about its parameters. (real or choice param, min/max, what options it can take, etc)

**Comment by thnkim** [comment]
Wow! very quick response! Sorry that I missed your comment :) 

In https://github.com/BVLC/caffe/tree/master/examples/cifar10, there is the file, cifar10_full_sigmoid_train_test_bn.prototxt. It has BatchNorm.

And you can see Caffe's BatchNormLayer at http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1BatchNormLayer.html.

Thank you!

**Comment by hctomkins** [comment]
Hi,
I have dropped in the node, but I couldn't find any example prototxts where the values where not default, so only the default 'use global average' computation is included, which is standard for most networks. Do you have any better examples? The current implementation I have just committed should be fine for most networks.
