### ISSUE TITLE
screen shot is not found

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [Chasvortex/caffe-gui-tool#5]
Hi, 
The links to scree shots seems to be broken.

**Comment by oscartheking** [comment]
And installation procedure and usage section also need screenshots.

**Comment by hctomkins** [comment]
Acknowledged - This is due to dropbox removing their support for public links. Will be fixed in the coming weeks.

**Comment by hctomkins** [comment]
Finally closed. Sorry for the delays.
