### ISSUE TITLE
How to construct layers and create connection between them

### ISSUE THREAD

**Issue by riyadhlewis** [Chasvortex/caffe-gui-tool#6]
Hello Hugh,
I have installed blender and successfully added your addons. I can get the run cafe tools when I switch to node editor. I have few questions here:
1- How to create neural network layers using the graph editor and how to establish connection among them? Do you have a recorded video that you can share? 
2- I tried to load an MNIST caffe model files (train test, deploy, and solver files) in their corresponding fields, then clicked the Load solution button. My expectation was to see the network loaded in the node editor. Nothing happened though.
I am so eager to hear from you.

Regards,

Riyadh Kenaya

**Comment by hctomkins** [comment]
Mentioned solved in issue #7
